### PR TITLE
Add Google PaLM API link

### PR DESCRIPTION
**Pull request by zyrain**

### CODE REVIEW

**Comment by Hannibal046** [comment]
Hi, thanks for your contribution! Could you please verify if this is the API for PaLM or for Flan-PaLM?

**Comment by zyrain** [comment]
Ah, good catch.  It looks like only the base PaLM (April 22), but they say it's going to be a multi-model interface.

**Comment by zyrain** [comment]
Also, it looks like it's not quite public yet, so perhaps my edit is premature.

**Comment by Hannibal046** [comment]
Thank you all the same. Maybe we could postpone this PR until we are clear about the LLM behind and the release of available API.

**Pull request closed without merging**
